name = "hackthon-x-websocket"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[vars]
FRONTEND_URL = "http://localhost:3000"

[observability.logs]
enabled = false

# Durable Objects for WebSocket sessions
[[durable_objects.bindings]]
name = "WEBSOCKET_SESSIONS"
class_name = "WebSocketSession"

# Durable Objects migrations
[[migrations]]
tag = "v1"
new_sqlite_classes = ["WebSocketSession"]

# Environment variables (set via wrangler secret)
# DATABASE_URL = "postgresql://..." (use: wrangler secret put DATABASE_URL)
# OPENAI_API_KEY = "sk-..." (use: wrangler secret put OPENAI_API_KEY)

